//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOrders.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClosedItem
    {
        public long ID { get; set; }
        public Nullable<long> CloseId { get; set; }
        public Nullable<long> OrderItemId { get; set; }
        public string ItemPrice { get; set; }
        public string OrderedQuantityItems { get; set; }
        public string OrderedPackages { get; set; }
        public string TotalPrice { get; set; }
        public string RemaindedQuantityToCl { get; set; }
        public string RemianedPriceToClose { get; set; }
    
        public virtual ClosedOrder ClosedOrder { get; set; }
        public virtual OrderItem OrderItem { get; set; }
    }
}
