//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOrders.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
            this.RequestOrders = new HashSet<RequestOrder>();
            this.ClosedOrders = new HashSet<ClosedOrder>();
        }
    
        public long ID { get; set; }
        public long VendorId { get; set; }
        public Nullable<System.DateTime> OpendDate { get; set; }
        public Nullable<System.DateTime> Close_Date { get; set; }
        public Nullable<System.TimeSpan> CloseTime { get; set; }
        public string Status { get; set; }
        public string AccountNo { get; set; }
        public string AccountName { get; set; }
        public string PhoneNumber { get; set; }
        public string RecievePlace { get; set; }
        public string RecievePerson { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestOrder> RequestOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClosedOrder> ClosedOrders { get; set; }
    }
}
