//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOrders.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestedOrderInvoice
    {
        public long Id { get; set; }
        public Nullable<long> requestId { get; set; }
        public byte[] ScanOfInvoice { get; set; }
        public string ScanOfInvoicePath { get; set; }
        public string fileName { get; set; }
    
        public virtual RequestOrder RequestOrder { get; set; }
    }
}
