//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOrders.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequestOrder()
        {
            this.RequestOrderItems = new HashSet<RequestOrderItem>();
            this.RequestedOrderInvoices = new HashSet<RequestedOrderInvoice>();
        }
    
        public long ID { get; set; }
        public long UserId { get; set; }
        public long OrderId { get; set; }
        public decimal TotalPrice { get; set; }
        public byte[] ScanOfInvoice { get; set; }
        public string Status { get; set; }
        public string RequesterName { get; set; }
        public string RequesterBlockNo { get; set; }
        public string RequesterPhone { get; set; }
        public string EnteredBy { get; set; }
        public string ScanOfInvoicePath { get; set; }
        public string fileName { get; set; }
    
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestOrderItem> RequestOrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestedOrderInvoice> RequestedOrderInvoices { get; set; }
    }
}
